data:extend({
  {
    type = "string-setting",
    name = "vsi-vehicle-types",
    setting_type = "startup",
    default_value = "spider-and-car",
    allowed_values = { "spider", "spider-and-car" },
    order = "a",
  },
  {
    type = "bool-setting",
    name = "vsi-enabled",
    setting_type = "runtime-per-user",
    default_value = true,
    order = "a",
  },
  {
    type = "int-setting",
    name = "vsi-interval",
    setting_type = "runtime-per-user",
    default_value = 15,
    allowed_values = { 5, 15, 30, 60 },
    order = "b",
  },
  {
    type = "bool-setting",
    name = "vsi-share-robots",
    setting_type = "runtime-per-user",
    default_value = true,
    order = "ba",
  },
  {
    type = "bool-setting",
    name = "vsi-return-on-exit",
    setting_type = "runtime-per-user",
    default_value = true,
    order = "c",
  },
  {
    type = "bool-setting",
    name = "vsi-require-roboport",
    setting_type = "runtime-per-user",
    default_value = true,
    order = "d",
  },
  {
    type = "int-setting",
    name = "vsi-max-ghosts",
    setting_type = "runtime-global",
    default_value = 5000,
    minimum_value = 100,
    maximum_value = 50000,
    order = "e",
  },
})
